const testData = [
    {
    id: 1,
    name: "White-Schulist",
    url: "https://github.io/tortor/risus/dapibus/augue/vel/accumsan/tellus.png",
    address: "9 2nd Crossing",
    city: "Lake Charles",
    state: "LA",
    postal_code: "70607",
    latitude: 30.1244,
    longitude: -93.1835,
    monday_open: "8:07 AM",
    monday_close: "7:42 PM",
    tuesday_open: "6:01 AM",
    tuesday_close: "6:54 PM",
    wednesday_open: "7:16 AM",
    wednesday_close: "5:35 PM",
    thursday_open: "7:06 AM",
    thursday_close: "5:00 PM",
    friday_open: "8:46 AM",
    friday_close: "6:08 PM",
    saturday_open: "9:19 AM",
    saturday_close: "4:41 PM",
    sunday_open: "8:33 AM",
    sunday_close: "9:08 PM"
    },
    {
    id: 2,
    name: "Hamill Group",
    url: "https://hibu.com/eros/elementum/pellentesque/quisque/porta.jsp",
    address: "9 Derek Place",
    city: "Missoula",
    state: "MT",
    postal_code: "59806",
    latitude: 47.116,
    longitude: -114.0498,
    monday_open: "6:47 AM",
    monday_close: "4:10 PM",
    tuesday_open: "8:09 AM",
    tuesday_close: "7:32 PM",
    wednesday_open: "6:11 AM",
    wednesday_close: "9:03 PM",
    thursday_open: "7:13 AM",
    thursday_close: "6:33 PM",
    friday_open: "9:56 AM",
    friday_close: "8:38 PM",
    saturday_open: "6:06 AM",
    saturday_close: "5:04 PM",
    sunday_open: "7:38 AM",
    sunday_close: "8:37 PM"
    },
    {
    id: 3,
    name: "Muller Group",
    url: "https://ning.com/ante/ipsum/primis/in/faucibus/orci/luctus.js",
    address: "0 Sachtjen Pass",
    city: "Wichita",
    state: "KS",
    postal_code: "67210",
    latitude: 37.6379,
    longitude: -97.2613,
    monday_open: "8:32 AM",
    monday_close: "9:47 PM",
    tuesday_open: "8:39 AM",
    tuesday_close: "8:14 PM",
    wednesday_open: "8:19 AM",
    wednesday_close: "9:27 PM",
    thursday_open: "6:07 AM",
    thursday_close: "4:50 PM",
    friday_open: "6:09 AM",
    friday_close: "9:07 PM",
    saturday_open: "6:34 AM",
    saturday_close: "7:31 PM",
    sunday_open: "7:44 AM",
    sunday_close: "9:31 PM"
    },
    {
    id: 4,
    name: "Oberbrunner-Veum",
    url: "http://seesaa.net/vitae/consectetuer/eget/rutrum/at/lorem.jpg",
    address: "9 Summerview Pass",
    city: "Los Angeles",
    state: "CA",
    postal_code: "90050",
    latitude: 33.7866,
    longitude: -118.2987,
    monday_open: "9:37 AM",
    monday_close: "9:56 PM",
    tuesday_open: "7:52 AM",
    tuesday_close: "4:53 PM",
    wednesday_open: "8:42 AM",
    wednesday_close: "4:18 PM",
    thursday_open: "6:17 AM",
    thursday_close: "9:55 PM",
    friday_open: "9:40 AM",
    friday_close: "8:23 PM",
    saturday_open: "6:43 AM",
    saturday_close: "4:00 PM",
    sunday_open: "8:58 AM",
    sunday_close: "4:46 PM"
    },
    {
    id: 5,
    name: "Zulauf, Lubowitz and Mann",
    url: "http://yandex.ru/mauris/eget/massa/tempor/convallis/nulla/neque.js",
    address: "32 New Castle Parkway",
    city: "Washington",
    state: "DC",
    postal_code: "20456",
    latitude: 38.8981,
    longitude: -77.0401,
    monday_open: "7:14 AM",
    monday_close: "6:48 PM",
    tuesday_open: "9:45 AM",
    tuesday_close: "6:08 PM",
    wednesday_open: "7:45 AM",
    wednesday_close: "9:16 PM",
    thursday_open: "6:12 AM",
    thursday_close: "9:43 PM",
    friday_open: "7:00 AM",
    friday_close: "5:22 PM",
    saturday_open: "8:19 AM",
    saturday_close: "7:52 PM",
    sunday_open: "8:02 AM",
    sunday_close: "8:33 PM"
    },
    {
    id: 6,
    name: "Halvorson, Nitzsche and Shields",
    url: "https://wikimedia.org/dolor/morbi.aspx",
    address: "5915 Dahle Pass",
    city: "Miami",
    state: "FL",
    postal_code: "33175",
    latitude: 25.7341,
    longitude: -80.4068,
    monday_open: "8:53 AM",
    monday_close: "9:08 PM",
    tuesday_open: "6:30 AM",
    tuesday_close: "4:27 PM",
    wednesday_open: "8:52 AM",
    wednesday_close: "4:41 PM",
    thursday_open: "8:22 AM",
    thursday_close: "9:44 PM",
    friday_open: "6:57 AM",
    friday_close: "7:33 PM",
    saturday_open: "9:59 AM",
    saturday_close: "5:56 PM",
    sunday_open: "8:42 AM",
    sunday_close: "7:42 PM"
    },
    {
    id: 7,
    name: "Simonis and Sons",
    url: "https://miibeian.gov.cn/sapien/sapien/non/mi/integer/ac.json",
    address: "76 Texas Point",
    city: "El Paso",
    state: "TX",
    postal_code: "79928",
    latitude: 31.6631,
    longitude: -106.1401,
    monday_open: "7:39 AM",
    monday_close: "7:59 PM",
    tuesday_open: "9:42 AM",
    tuesday_close: "8:39 PM",
    wednesday_open: "9:54 AM",
    wednesday_close: "6:59 PM",
    thursday_open: "7:59 AM",
    thursday_close: "6:05 PM",
    friday_open: "7:11 AM",
    friday_close: "4:59 PM",
    saturday_open: "9:08 AM",
    saturday_close: "4:14 PM",
    sunday_open: "8:47 AM",
    sunday_close: "8:39 PM"
    },
    {
    id: 8,
    name: "Hansen LLC",
    url: "http://usgs.gov/parturient/montes/nascetur/ridiculus/mus.json",
    address: "01796 Leroy Court",
    city: "Kansas City",
    state: "KS",
    postal_code: "66105",
    latitude: 39.085,
    longitude: -94.6356,
    monday_open: "6:39 AM",
    monday_close: "4:13 PM",
    tuesday_open: "9:39 AM",
    tuesday_close: "8:57 PM",
    wednesday_open: "9:52 AM",
    wednesday_close: "9:24 PM",
    thursday_open: "8:16 AM",
    thursday_close: "5:34 PM",
    friday_open: "9:50 AM",
    friday_close: "8:28 PM",
    saturday_open: "6:57 AM",
    saturday_close: "4:29 PM",
    sunday_open: "8:00 AM",
    sunday_close: "5:50 PM"
    },
    {
    id: 9,
    name: "Turner and Sons",
    url: "https://skyrock.com/aenean.png",
    address: "9 Fieldstone Alley",
    city: "Reston",
    state: "VA",
    postal_code: "20195",
    latitude: 38.8318,
    longitude: -77.2888,
    monday_open: "9:24 AM",
    monday_close: "4:43 PM",
    tuesday_open: "7:06 AM",
    tuesday_close: "8:41 PM",
    wednesday_open: "8:17 AM",
    wednesday_close: "6:31 PM",
    thursday_open: "9:33 AM",
    thursday_close: "5:06 PM",
    friday_open: "8:20 AM",
    friday_close: "8:03 PM",
    saturday_open: "8:46 AM",
    saturday_close: "4:23 PM",
    sunday_open: "9:56 AM",
    sunday_close: "4:23 PM"
    },
    {
    id: 10,
    name: "Bechtelar and Sons",
    url: "https://jimdo.com/elementum/nullam/varius/nulla.xml",
    address: "89977 Upham Lane",
    city: "Arlington",
    state: "VA",
    postal_code: "22234",
    latitude: 38.8808,
    longitude: -77.113,
    monday_open: "9:40 AM",
    monday_close: "8:38 PM",
    tuesday_open: "8:29 AM",
    tuesday_close: "8:03 PM",
    wednesday_open: "9:06 AM",
    wednesday_close: "9:17 PM",
    thursday_open: "6:04 AM",
    thursday_close: "5:43 PM",
    friday_open: "6:33 AM",
    friday_close: "9:05 PM",
    saturday_open: "6:37 AM",
    saturday_close: "7:21 PM",
    sunday_open: "8:06 AM",
    sunday_close: "8:27 PM"
    },
    {
    id: 11,
    name: "Kirlin-Haag",
    url: "https://cbslocal.com/nam/ultrices/libero/non/mattis/pulvinar.xml",
    address: "50 Schmedeman Hill",
    city: "Saint Petersburg",
    state: "FL",
    postal_code: "33705",
    latitude: 27.7391,
    longitude: -82.6435,
    monday_open: "7:34 AM",
    monday_close: "7:06 PM",
    tuesday_open: "7:34 AM",
    tuesday_close: "6:43 PM",
    wednesday_open: "9:52 AM",
    wednesday_close: "7:40 PM",
    thursday_open: "9:20 AM",
    thursday_close: "4:24 PM",
    friday_open: "6:08 AM",
    friday_close: "9:32 PM",
    saturday_open: "9:52 AM",
    saturday_close: "4:05 PM",
    sunday_open: "7:42 AM",
    sunday_close: "6:19 PM"
    },
    {
    id: 12,
    name: "Lynch, Jast and Davis",
    url: "https://github.io/sed/magna/at.jsp",
    address: "64 Lake View Road",
    city: "Temple",
    state: "TX",
    postal_code: "76505",
    latitude: 31.0363,
    longitude: -97.492,
    monday_open: "6:45 AM",
    monday_close: "5:30 PM",
    tuesday_open: "6:38 AM",
    tuesday_close: "6:52 PM",
    wednesday_open: "9:54 AM",
    wednesday_close: "9:29 PM",
    thursday_open: "6:52 AM",
    thursday_close: "4:20 PM",
    friday_open: "6:10 AM",
    friday_close: "7:27 PM",
    saturday_open: "8:58 AM",
    saturday_close: "6:46 PM",
    sunday_open: "7:48 AM",
    sunday_close: "5:09 PM"
    },
    {
    id: 13,
    name: "Gusikowski-Schiller",
    url: "http://lulu.com/mauris/viverra/diam/vitae.jpg",
    address: "94152 Clemons Terrace",
    city: "Albany",
    state: "GA",
    postal_code: "31704",
    latitude: 31.55,
    longitude: -84.0612,
    monday_open: "8:08 AM",
    monday_close: "5:09 PM",
    tuesday_open: "6:44 AM",
    tuesday_close: "8:10 PM",
    wednesday_open: "9:18 AM",
    wednesday_close: "8:24 PM",
    thursday_open: "6:50 AM",
    thursday_close: "7:42 PM",
    friday_open: "8:52 AM",
    friday_close: "6:17 PM",
    saturday_open: "7:29 AM",
    saturday_close: "7:56 PM",
    sunday_open: "6:06 AM",
    sunday_close: "4:20 PM"
    },
    {
    id: 14,
    name: "Littel, Lockman and Powlowski",
    url: "https://hatena.ne.jp/mattis/pulvinar/nulla/pede/ullamcorper.html",
    address: "038 Sauthoff Drive",
    city: "New Haven",
    state: "CT",
    postal_code: "06505",
    latitude: 41.3057,
    longitude: -72.7799,
    monday_open: "6:33 AM",
    monday_close: "4:01 PM",
    tuesday_open: "7:41 AM",
    tuesday_close: "4:11 PM",
    wednesday_open: "7:29 AM",
    wednesday_close: "9:11 PM",
    thursday_open: "7:09 AM",
    thursday_close: "8:01 PM",
    friday_open: "9:12 AM",
    friday_close: "7:55 PM",
    saturday_open: "9:22 AM",
    saturday_close: "4:16 PM",
    sunday_open: "9:11 AM",
    sunday_close: "4:46 PM"
    },
    {
    id: 15,
    name: "Rohan, Wiegand and Wisozk",
    url: "https://exblog.jp/a/nibh/in/quis/justo/maecenas/rhoncus.js",
    address: "7841 Pine View Court",
    city: "Lancaster",
    state: "CA",
    postal_code: "93584",
    latitude: 33.7866,
    longitude: -118.2987,
    monday_open: "8:41 AM",
    monday_close: "5:11 PM",
    tuesday_open: "6:24 AM",
    tuesday_close: "4:40 PM",
    wednesday_open: "9:13 AM",
    wednesday_close: "5:42 PM",
    thursday_open: "7:09 AM",
    thursday_close: "8:05 PM",
    friday_open: "8:59 AM",
    friday_close: "5:24 PM",
    saturday_open: "8:06 AM",
    saturday_close: "7:20 PM",
    sunday_open: "9:46 AM",
    sunday_close: "8:03 PM"
    },
    {
    id: 16,
    name: "Gaylord-Hilll",
    url: "http://unblog.fr/est/donec/odio/justo/sollicitudin.jsp",
    address: "635 Sunnyside Terrace",
    city: "Harrisburg",
    state: "PA",
    postal_code: "17121",
    latitude: 40.2944,
    longitude: -76.8938,
    monday_open: "9:16 AM",
    monday_close: "6:46 PM",
    tuesday_open: "6:22 AM",
    tuesday_close: "8:10 PM",
    wednesday_open: "9:40 AM",
    wednesday_close: "7:04 PM",
    thursday_open: "6:02 AM",
    thursday_close: "6:01 PM",
    friday_open: "9:26 AM",
    friday_close: "5:40 PM",
    saturday_open: "6:47 AM",
    saturday_close: "8:28 PM",
    sunday_open: "6:48 AM",
    sunday_close: "6:18 PM"
    },
    {
    id: 17,
    name: "Kling Inc",
    url: "http://msn.com/integer/a/nibh/in/quis/justo.aspx",
    address: "46010 Center Street",
    city: "Austin",
    state: "TX",
    postal_code: "78744",
    latitude: 30.1876,
    longitude: -97.7472,
    monday_open: "7:11 AM",
    monday_close: "6:44 PM",
    tuesday_open: "9:02 AM",
    tuesday_close: "4:52 PM",
    wednesday_open: "7:21 AM",
    wednesday_close: "5:17 PM",
    thursday_open: "6:10 AM",
    thursday_close: "5:51 PM",
    friday_open: "9:46 AM",
    friday_close: "9:15 PM",
    saturday_open: "7:58 AM",
    saturday_close: "9:28 PM",
    sunday_open: "9:46 AM",
    sunday_close: "8:48 PM"
    },
    {
    id: 18,
    name: "Emmerich-Bauch",
    url: "https://wikipedia.org/est/phasellus/sit/amet/erat/nulla.html",
    address: "62 Waubesa Center",
    city: "Newark",
    state: "NJ",
    postal_code: "07195",
    latitude: 40.7918,
    longitude: -74.2452,
    monday_open: "9:23 AM",
    monday_close: "4:18 PM",
    tuesday_open: "7:28 AM",
    tuesday_close: "4:04 PM",
    wednesday_open: "8:53 AM",
    wednesday_close: "6:58 PM",
    thursday_open: "7:59 AM",
    thursday_close: "7:25 PM",
    friday_open: "7:31 AM",
    friday_close: "9:04 PM",
    saturday_open: "8:59 AM",
    saturday_close: "7:41 PM",
    sunday_open: "8:38 AM",
    sunday_close: "4:23 PM"
    },
    {
    id: 19,
    name: "Oberbrunner, Langosh and Maggio",
    url: "http://sphinn.com/vel/accumsan/tellus/nisi.js",
    address: "667 Washington Circle",
    city: "Herndon",
    state: "VA",
    postal_code: "22070",
    latitude: 38.9776,
    longitude: -77.386,
    monday_open: "9:32 AM",
    monday_close: "8:09 PM",
    tuesday_open: "6:19 AM",
    tuesday_close: "8:57 PM",
    wednesday_open: "9:42 AM",
    wednesday_close: "6:57 PM",
    thursday_open: "8:43 AM",
    thursday_close: "9:30 PM",
    friday_open: "9:24 AM",
    friday_close: "6:32 PM",
    saturday_open: "6:55 AM",
    saturday_close: "5:19 PM",
    sunday_open: "8:55 AM",
    sunday_close: "6:18 PM"
    },
    {
    id: 20,
    name: "Nader-Hegmann",
    url: "http://vistaprint.com/luctus.aspx",
    address: "346 Hauk Park",
    city: "Toledo",
    state: "OH",
    postal_code: "43635",
    latitude: 41.6868,
    longitude: -83.4394,
    monday_open: "7:23 AM",
    monday_close: "5:51 PM",
    tuesday_open: "6:00 AM",
    tuesday_close: "9:40 PM",
    wednesday_open: "7:43 AM",
    wednesday_close: "4:48 PM",
    thursday_open: "6:40 AM",
    thursday_close: "9:22 PM",
    friday_open: "8:55 AM",
    friday_close: "7:45 PM",
    saturday_open: "7:55 AM",
    saturday_close: "7:30 PM",
    sunday_open: "7:11 AM",
    sunday_close: "7:37 PM"
    }
    ]

    export default testData;